### ISSUE TITLE
How does this deviate from Agario protocol?

### ISSUE THREAD

**Issue by EnTerr** [JaraLowell/OgarServ#142] opened 2016-05-12 05:32 UTC
So i have written a 3rd party client for smart tv platform, based on http://agar.gcommer.com/Protocol alone. No javascript. This was working fine with the public Agar.io servers till last week they switched to new protocol (type 6, 255 packets etc).

I am trying to salvage my client and make it able to connect to alternative servers. Cue http://ogar.mivabe.nl/master . However, after my client connects, it cannot control the blob - the cells stays in one place regardless how i try to follow my cursor. 

So i wonder - in what ways is the protocol of OgarServ different from old Agario one? There is some caveat, i must be missing something if these servers were working with agar.io browser client...

**Comment by EnTerr** [comment] 2016-05-12 05:58
One thing i notice is client and server exchange 0x5a packets. What the is 5a (dec 90)?

**Comment by EnTerr** [comment] 2016-05-12 09:13
I think i figured a reason - my client was sending over websockets in TEXT (defualt) mode. Agario servers apparently don't care which way but Ogar expects BINARY, it seems. Explicitly sending as binary made Ogar hear the directions.

Still, what is 0x5a packet from the client? And what's 0x5a packet from the server?

**Comment by JaraLowell** [comment] 2016-05-12 13:32
Agar.io changed there protocol now 3x, last weeks one being the up most annoying. You basicly can see the what is send, in PacketHandler.js In your case what can go wrong is how your client handles the move requests there 2 places in the client where this has to be adressed. Extremly old clients use getInt32 for pos x & y while newer clients use getInt16 this is in the nodes update package.

My server uses package 90 to send server info like number of players. You not per say have to use it and your client should run fine with out it.

**Comment by EnTerr** [comment] 2016-05-12 17:59
@JaraLowell wait what? how is this possible, using int16 instead of int32? i saw something like that with mouse cursor/movement sent - but how can the server tell which one is it getting? 

i use 4 byte ints because this http://agar.gcommer.com/index.php?title=Protocol#Set_Direction_.28Opcode_16.29 - and nobody has described it otherwise. Just checked (wireshark) and current Agar.io sends the mouse packet (16) as 13-byte.

Any more details on such deviations? is there a doc

**Comment by JaraLowell** [comment] 2016-05-12 20:36
Not about server, about client OgarServ already knows when it is what one (size of package) but the client when it recieves an int32 and handles it as an int16 wel yah that goes.. mega wrong.

Also for current agar.io if i remeber they add an 'key' to the value the server sends bit wise. so they take int8 and do an `value & version number` bit check. If so then any number received would be value + bit value version number. Correct me if i am wrong though.

So check in your client how and what it wants for node updates int16 or int32 one is old protocol and the other new. (believe 16 was new)

**Comment by EnTerr** [comment] 2016-05-13 00:58
I am learning more about Jara's OgarServ as i go and seems you have deviated from Ogar and Agar in some cases. Not blaming but:

How can i tell what version is being run?! So i connect over websockets and... in general don't know which server am i talking to. Do you support say `server_version` extension in packet 64? http://agar.gcommer.com/index.php?title=Protocol#Game_area_size_.28opcode_64.29

The idea being, (a non-JS) client connects to the server and can figure out what protocol "dialect" it talks, so can adjust its "language". Also i notice that from http://ogar.mivabe.nl/master list, mine works with some of the servers but not with others - which makes me think there might be different versions - one more reason to know the "flavor" and version of the server on the other side?

**Comment by JaraLowell** [comment] 2016-05-13 01:59
OgarServ supports old and older.. lol cant say current as Agar.IO changed there whole structure last week and will thus be a while before we can support that

in gameserver.ini
serverVersion = 1 / 0
Protocal version of client (v561.20 and up is 1, while v561.20 and below is 0)

OgarServ just has also Chat and LifeStats package to Client (id 90)

**Comment by EnTerr** [comment] 2016-05-13 03:41
No-no, you don't understand!
I don't want to download and install OgarServ nor can use a javascript client. So "gameserver.ini" means nothing.

I have written a client from scratch, that could talk Agario protocol (till last week, naturally). Now i am ready to modify it to support OgarServ too. However there is no established way now after i connect to a particular IP to be able to tell is this Agario or Ogar or OgarServ - and if the latter, which version is it?

Somewhere somehow OgarServ should be **sending ID and version info** to the client. I am proposing that to be in in packet 64, like Agario does. Say my client connects to one of the OgarServ's out there - how does it know if serverVersion = 1 or serverVersion = 0 in gameserver.ini ?! It can't...

**Comment by JaraLowell** [comment] 2016-05-13 04:23
Ooh,. Wel OgarServ tells what version it is, `OgarServ 1.6.4Rev308 by Jara Lowell` in package ID 64
see `packet/SetBorder.js` for it :smiling_imp:

**Comment by EnTerr** [comment] 2016-05-13 07:23
Indeed it does! 
Ha, that's weird though - the http://ogar.mivabe.nl/?ip=149.56.134.117:555 i tested does NOT report the version in ID 64. So it should have told me but did not. i wonder if it's over 6mo old or mod-ed ...

**Comment by Ciao121** [comment] 2016-05-13 10:09
@EnTerr,
Hi, is you client available on github or anywhere?
Thank you!

**Comment by EnTerr** [comment] 2016-05-13 20:05
Indeed it does! My bad, i thought my code was printing version string to console.

Are there any stats how many servers are running which version? Seems as-is i am compatible with 1.6.4 but from a quick sample of a dozen servers seems most are OgarServ 1.5.9? 

PS. here are some stats i collected manually from ~80 servers:
- 9% have v1.6.x (my code speaks this)
- 52% have v1.5.x (either my code needs re-work or "legacy" mode)
- 24% no connection (dead or firewall?)
- 15% connect but weird (no info in 64; mostly gets kicked out)

**Comment by JaraLowell** [comment] 2016-05-13 22:46
OgarServ can run in v561.20 and up and older versions. As explained the difference is the int16 and int32 for node updates (cells), in that it not the version of server but client they use.

http://ogar.mivabe.nl/master

Agar.io mode = v561.20 and up
Private mode = Old Clients

**Comment by EnTerr** [comment] 2016-05-13 23:12
Thanks for explaining the "Client Type" column! Meaning was not obvious.

Pre v561.20... that was almost a year ago, right?  [July 13th 2015](https://github.com/forairan/Agar.io-Protocol/commit/e265d8960413e8a89bac8a3a1b1912d0e29738f4) was 2 months before this project even started. 

And yet most of the servers (55%) say "private" - why would somebody try to be compatible with something that ancient? Maybe bad choice of name "private" vs "agario"

**Comment by JaraLowell** [comment] 2016-05-13 23:27
Because the web client handed out on ragezone.com is that old. And seeing web owners have no clue how to make an simple adjustment in an js file they kept running under that old code.

**Comment by EnTerr** [comment] 2016-05-14 09:36
So, here is my difficulty - say my client connects to OgarServ by given IP:port - how can it tell if the  server is running in **normal** (aka "agar.io", 32bit x,y) or **legacy** (aka "private", 16bit x,y) mode? 

I saw/like how OgarServ auto-detects the client protocol by mouse packet size but I don't think i can auto-detect it in the client by the Update packet from the server, since it's variable size, 0 terminated.

**Comment by JaraLowell** [comment] 2016-05-14 12:44
Actually you can, you need look in my client over at ogar.mivabe.nl, in there I detect the server and then set a flag to use this. :smiling_imp:

**Comment by EnTerr** [comment] 2016-05-14 19:19
@JaraLowell - `aio` in http://ogar.mivabe.nl/js/gameclient.js ? Why would you be checking if player_id > 100000 - does OgarServ purposely send <1e5 for legacy and >1e5 for normal ? (Where in the code is this determined btw?)

What about other servers like Ogar or Agario - is it guaranteed they always send >1e5, given they use the "normal" protocol? My client wants to work with them all, you know.

I ran into this issue #54 - seems like a very clever way to avoid problems by server auto-adapting. I'll drop a line there about the "how"

**Comment by EnTerr** [comment] 2016-05-16 12:43
In **good news**, i added to my client the shoddy "legacy" mode (x,y coords float64 for pointer, int16 from blobs) and my compatibility jumped substantially, the breakdown now is:
- 61% works, = v1.6/1.5, in normal or legacy mode.
- 15% weird (half are kicks because of origin "security", TBD the other half - they switch to Play but don't react to cursor)
- 24% no connection (likely firewalled?)

In **bad news**, i still have no way to "divine" if the server is in _normal_ (int32/int32) or _legacy_ (int16/float64) mode when given a URL, so have to manually specify that.

**Comment by EnTerr** [comment] 2016-05-17 09:47
Ok, so somehow there is "3rd dialect" of the protocol used by some OgarServs - they use int32 for server update packet but float64 for client cursor packet. (As a reminder, "legacy" is int16/float64 and "contemporary" is int32/int32). WTF. Examples of such servers are 188.165.221.113, 51.255.142.32, 95.141.32.132

@JaraLowell - any idea why this 3rd dialect or how did it happen? Does it mean they took the version before https://github.com/JaraLowell/OgarServ/commit/7d243141f204b775f1af7cbacabb410062f4330f

**Comment by JaraLowell** [comment] 2016-05-17 12:59
Some like to be special i guess, no idea really; My server supports and runs as you see it. I have trully no intentions to support any more then i do. I at this moment not even know if i seek to support even current style of the original server but will see

**Comment by EnTerr** [comment] 2016-05-17 17:59
Those three servers above are from the "master tracker" list, so it must be older version of your server. I doubt they modified the code to be "special", rather must have downloaded before July 2015's int32 x,y cursor direction was added [beginning of Oct 2015](https://github.com/JaraLowell/OgarServ/commit/7d243141f204b775f1af7cbacabb410062f4330f). They don't report the server version in World Size (64), which was added [end of Oct 2015](https://github.com/JaraLowell/OgarServ/commit/a94af7b7f57550898f4dd59193898c21445f4dee).

The reason i am asking is trying to understand what "dialects" of the protocol are out there, so that my client can be universal enough connecting. Amongst your flock of tracked servers, this particular variation  (int32/float64) is rare 3%, where the rest (int32/int32 vs int16/float64) is approx. even 50/50 split.

**Comment by JaraLowell** [comment] 2016-05-17 18:30
Some of the people never updated the servers; they liked the old view or old way of how splitting was. Some enjoy the new way or wanted it; What variations there be all i dont know though obviously a package length should be able to help in most deciding.

**Comment by Barbosik** [comment] 2016-05-23 06:59
**EnTerr**>> _I am trying to salvage my client and make it able to connect to alternative servers. Cue http://ogar.mivabe.nl/master . However, after my client connects, it cannot control the blob - the cells stays in one place regardless how i try to follow my cursor._

Wow! Cool site! It's good finding for my client :)

I have the same issue with mouse event. It's strange because it doesn't works at all when I select protocol 4 instead of 5. May be I changed something a little for some private serve. Needs to check it. Actually I forgot what I changed for protocol 4, because I played for a long time on agario. But now it's the time to switch on private servers :)

Is there any web service to obtain the server list in json?

**Comment by JaraLowell** [comment] 2016-05-23 13:57
No, i provide the site as is, no json slash xml file to get. Need get least a a cent a day for hosting it :smiling_imp: Mouse events have bin explained, and really i think protocol 4 and older, should really not be used no more, that my personal view on that though. Only 5 and posibly 6 to stay up to date with agar.io if some wish that.

**Comment by EnTerr** [comment] 2016-05-23 17:06
@Barbosik - read this thread further incl. my comment https://github.com/JaraLowell/OgarServ/issues/142#issuecomment-219670194 . Some servers expect mouse events as int32 (contemporary), some as float64 (legacy from June-July 2015), and very very few as int16 (pre-June 2015). You can figure out which from the table column "Client Type", where "Agar.io" means int32 and "private" is float64 - or you can run your client against the IP and see if the session "bombs", malfunctions in some sense

**Comment by Barbosik** [comment] 2016-05-24 07:39
**EnTerr**: 
I found that servers marked as "Private" actually working with protocol 4 (I didn't changed protocol implementation, I just select protocol 4 in my client and it works well).

And servers marked as "Agar.io" actually working with protocol 5. Some of them works ok. But some of them just ignores mouse  control.

Probably those bad protocol 5 servers using int16 for mouse, need to test it. 

But the problem is that **there is no way to understand which mouse format exactly is needed**.
Because I don't see any errors on protocol layer. As I don't see any errors on engine level too. 
Both servers (good and bad one) works well with protocol=5, but the bad one just ignores all mouse messages.

Here is config script for bad server:

```
#protocol 5 bad
sv_protocol 5
sv_origin "http://ogar.mivabe.nl"
connect 95.141.32.132:9003
```

Here is config script for good server:

```
#protocol 5 good
sv_protocol 5
sv_origin "http://ogar.mivabe.nl/"
connect 62.138.6.208:443
```

Both using protocol 5, but the first one ignores mouse messages.

Update: approved, bad server accepts only mouse message with the following structure:

| Offset | Type | Description |
| --- | --- | --- |
| 0 | int16 | x coord |
| 2 | int16 | y coord |
| 4 | uint32 | 0x00000000 |

This is a reason why those servers is almost empty. Because they using custom hand-made mouse message which is not supported by popular clients. And even more - there is no way to distinguish those servers from normal.

**Comment by Barbosik** [comment] 2016-05-24 08:39
**JaraLowell**: Need get least a a cent a day for hosting it

But it seems that you already has some money for ad on the site, isn't it? :)
Anyway your site is good. You did a great job! Thanks!

**Comment by EnTerr** [comment] 2016-05-24 20:18
@Barbosik - reading the wiki history of http://agar.gcommer.com/Protocol i figured (like i said) that must be some pre-June 2015 protocol, where mouse was sent int16. Like i said though, there are very very few of these - the other day when i tested there were only 3 in the master list, i feel free to ignore them.

I did not know that "legacy" mode was protocol number 4. But yes - there is no way to auto-detect if Ogar server is configured for protocol 4 or 5, other than a) try&catch for exeptions or b) rely on next-to-last column info from master list. The int16/int16 mouse i wouldn't worry about since so rare (could that been protocol 3?)

**Comment by Barbosik** [comment] 2016-05-26 06:57
**EnTerr**:  _that must be some pre-June 2015 protocol_

I played at that time with my client, may be I forgot something, but I don't remember that agario used int16 for mouse in the protocol 5. In the protocol 4 they used 2 x float64 (double) for mouse.
If I remember correctly, such int16 mouse mod was used on petridish in the end on 2015 or begin of 2016. But I have no idea what is benefit for such incompatible mod.

**Comment by EnTerr** [comment] 2016-05-26 08:58
@Barbosik - mouse might have been int16 between 12 and  27 July 2015,
see http://agar.gcommer.com/index.php?title=Protocol&diff=prev&oldid=157
and http://agar.gcommer.com/index.php?title=Protocol&type=revision&diff=277&oldid=274

**Comment by Barbosik** [comment] 2016-06-06 20:11
I added mouse packet type auto-detection in https://github.com/Barbosik/MultiOgar
It can recognize any known type of mouse packet by it's size.

**Closed as completed** 2016-07-21 02:13 UTC
